// Generated by Nevela from nevela/resources/category.json in the Laravel app.
// Laravel owns validation, authorization and persistence; this descriptor tells the
// Flare dashboard how to render the resource. Change fields in the JSON and run
// `php artisan nevela:generate`. Display-only options may go below the block.
import { defineResource, field } from "@flaredev/core";

export default defineResource({
  // nevela:generated:start hash=054be1b82a49
  name: "Category",
  table: "categories",
  slug: "categories",
  label: "Category",
  pluralLabel: "Categories",
  icon: "tags",
  group: "Catalogue",
  fields: {
    name: field.string(),
    slug: field.slug({ unique: true }),
    image: field.file(["image"], { required: false, list: true }),
    products: field.hasMany("Product", { foreignKey: "categoryId" }),
  },
  // nevela:generated:end
});
