// Generated by Nevela from nevela/resources/product.json in the Laravel app.
// Laravel owns validation, authorization and persistence; this descriptor tells the
// Flare dashboard how to render the resource. Change fields in the JSON and run
// `php artisan nevela:generate`. Display-only options may go below the block.
import { defineResource, field } from "@flaredev/core";

export default defineResource({
  // nevela:generated:start hash=e9df57418af6
  name: "Product",
  table: "products",
  slug: "products",
  label: "Product",
  pluralLabel: "Products",
  icon: "package",
  group: "Catalogue",
  fields: {
    name: field.string(),
    sku: field.string({ unique: true }),
    price: field.float({ format: "money" }),
    image: field.file(["image"], { required: false, list: true }),
    categoryId: field.belongsTo("Category"),
    active: field.boolean(),
    kind: field.enum(["stock","digital"]),
    notes: field.text({ required: false }),
  },
  // nevela:generated:end
});
